=== nick7/idascm-data/schema/configuration.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "definitions": {
    "argument": {
      "type": "object",
      "properties": {
        "type": {
          "title": "High-level argument type",
          "$ref": "#/definitions/type"
        },
        "enum": {
          "type": "string",
          "title": "Enumeration unique name",
          "pattern": "^([A-Z0-9_]+)$"
        },
        "operand_type": {
          "title": "Override operand type",
          "description": "NOTE: Type informaton byte will not be read with this property.",
          "$ref": "#/definitions/operand_type"
        }
      },
      "required": [ "type" ],
      "additionalProperties": false
    },
    "command": {
      "description": "Single command definition",
      "type": "object",
      "properties": {
        "name": {
          "$ref": "#/definitions/command_name"
        },
        "args": {
          "anyOf": [
            {
              "title": "Argument count",
              "description": "Short form for `[any, any, ...]`",
              "type": "integer",
              "minimum": -1,
              "maximum": 32
            },
            {
              "title": "Argument definition list",
              "type": "array",
              "items": {
                "anyOf": [
                  {
                    "title": "Argument type",
                    "$ref": "#/definitions/type"
                  },
                  {
                    "title": "Argument definition",
                    "$ref": "#/definitions/argument"
                  }
                ]
              },
              "maxItems": 32
            }
          ]
        },
        "format": {
          "title": "INI Command Format",
          "description": "Community Notation - SannyBuilder",
          "pattern": "^([a-zA-Z 0-9_\\-\\.%+=<>*/:,|~&^]+)$"
        },
        "flags": {
          "description": "Command flag list",
          "type": "array",
          "items": {
            "$ref": "#/definitions/command_flag"
          }
        },
        "desc": {
          "description": "Short command description",
          "type": "string"
        },
        "comment": {
          "description": "Any user text",
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "command_name": {
      "title": "Command Name",
      "description": "Rockstar Notation - UPPERCASE",
      "type": "string",
      "pattern": "^([A-Z_0-9]+|\\{|\\})$"
    },
    "command_flag": {
      "anyOf":[
        {
          "const": "stop",
          "title": "Don't process next address (`CF_STOP`)."
        },
        {
          "const": "branch",
          "title": "Branch execution flow (`CF_JUMP`).",
          "description": "Requires `address`, `mission` or `script` type."
        },
        {
          "const": "call",
          "title": "GOSUB-like command (`CF_CALL`).",
          "description": "Requires `branch` flag."
        },
        {
          "const": "return",
          "title": "Return from function.",
          "description": " Required for proper IDA analysis."
        },
        {
          "const": "condition",
          "title": "Modifies condition flag"
        },
        {
          "const": "conditional",
          "title": "Uses condition flag"
        },
        {
          "const": "function_call",
          "title": "Advanced function call with parameters and variable stack",
          "description": "NOTE: GTA:LCS and GTA:VCS only"
        },
        {
          "const": "switch",
          "title": "Switch idiom",
          "description": "NOTE: GTA:SA only"
        },
        {
          "const": "dependent",
          "title": "This command depends on previous one",
          "description": "(e.g. `SWITCH_CONTINUED`)"
        },
        {
          "const": "unsupported",
          "title": "No inplementation provided",
          "description": "Will crash execution process."
        },
        {
          "const": "macro",
          "title": "Compiler only high-level construction (e.g. variable declaration)"
        },
        {
          "const": "cleo",
          "description": "CLEO library extension"
        }
      ]
    },
    "operand_type": {
      "enum": [
        "unknown",
        "none",
        "local",
        "global",
        "timer",
        "local_array",
        "global_array",
        "string",
        "int0",
        "int8",
        "int16",
        "int32",
        "int64",
        "float0",
        "float8",
        "float16",
        "float16i",
        "float24",
        "float32",
        "string8",
        "string16",
        "string128"
      ]
    },
    "type": {
      "anyOf": [
        {
          "const": "unknown",
          "title": "Void type",
          "description": "This type should not be used directly."
        },
        {
          "const": "any",
          "title": "Any type",
          "description": "Default behaviour (acceptable in most cases)."
        },
        {
          "enum": [ "integer", "int" ],
          "title": "Variable size signed integer"
        },
        {
          "enum": [ "real", "float" ],
          "title": "Variable size floating point"
        },
        {
          "enum": [ "string" ],
          "title": "Any string type",
          "description": "NOTE: Explicit `operand_type` is required for GTA3 and GTA:VC."
        },
        {
          "enum": [ "variadic", "..." ],
          "title": "Variadic parameter list (ending with operand_type::none)"
        },
        {
          "const": "address",
          "title": "Subroutine or label address",
          "description": "Requires `branch` flag (Example: `GOTO` command)"
        },
        {
          "const": "mission",
          "title": "Mission ID (segment)"
        },
        {
          "const": "script",
          "title": "Streamable script ID"
        },
        {
          "const": "model",
          "title": "Model Identifier",
          "description": "Any in-game model ID"
        },
        {
          "const": "handle",
          "title": "Resource handle",
          "description": "Any in-game object (e.g. player, car, pickup)"
        },
        {
          "enum": [ "constant", "const" ],
          "title": "Immediate value argument",
          "description": "This argument is NOT a variable."
        },
        {
          "const": "variable",
          "title": "Any variable (local or global)",
          "description": "This argument can be changed by command"
        },
        {
          "const": "global",
          "title": "Abstract global variable (memory reference)"
        },
        {
          "const": "local",
          "title": "Abstract local variable (IDA register)"
        },
        {
          "enum": [ "constant_integer", "const_int" ],
          "title": "Immediate value integer"
        },
        {
          "enum": [ "constant_real", "const_float" ],
          "title": "Immediate value floating-point"
        },
        {
          "enum": [ "constant_string", "const_string" ],
          "title": "Immediate value string"
        },
        {
          "enum": [ "variable_integer", "variable_int" ],
          "title": "Any integer variable (local or global)"
        },
        {
          "enum": [ "global_integer", "global_int" ],
          "title": "Global integer variable"
        },
        {
          "enum": [ "local_integer", "local_int" ],
          "title": "Local integer variable"
        },
        {
          "enum": [ "variable_real", "variable_float" ],
          "title": "Any floating-point variable (local or global)"
        },
        {
          "enum": [ "global_real", "global_float" ],
          "title": "Global floating-point variable"
        },
        {
          "enum": [ "local_real", "local_float" ],
          "title": "Local floating-point variable"
        },
        {
          "const": "variable_string",
          "description": "Any string variable (local or global) (GTA:SA)"
        },
        {
          "const": "global_string",
          "title": "Global string variable (GTA:SA)"
        },
        {
          "const": "local_string",
          "title": "Local string variable (GTA:SA)"
        }
      ]
    },
    "meta": {
      "type": "object",
      "description": "Optional meta-information",
      "properties": {
        "timestamp": {
          "type": "string",
          "format": "date-time"
        },
        "author": {
          "type": "string"
        }
      }
    },
    "version": {
      "anyOf":[
        {
          "enum": [ "gta3", "gta3_ps2", "gta3_xbox", "gta3_pc", "gta3_pc_cleo", "gta3_anniversary", "gta3_definitive", "gta3_custom" ],
          "description": "Grand Theft Auto III"
        },
        {
          "enum": [ "gtavc", "gtavc_ps2", "gtavc_xbox", "gtavc_pc", "gtavc_pc_cleo", "gtavc_anniversary", "gtavc_definitive", "gtavc_custom" ],
          "description": "Grand Theft Auto: Vice City"
        },
        {
          "enum": [ "gtasa", "gtasa_ps2", "gtasa_xbox", "gtasa_pc", "gtasa_pc_cleo", "gtasa_anniversary", "gtasa_definitive", "gtasa_custom" ],
          "description": "Grand Theft Auto: San Andreas"
        },
        {
          "enum": [ "gtalcs", "gtalcs_ps2", "gtalcs_psp", "gtalcs_anniversary" ],
          "description": "Grand Theft Auto: Liberty City Stories"
        },
        {
          "enum": [ "gtavcs", "gtavcs_ps2", "gtavcs_psp" ],
          "description": "Grand Theft Auto: Vice City Stories"
        }
      ]
    }
  },
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "meta": {
      "$ref": "#/definitions/meta"
    },
    "version": {
      "description": "This configuration unique version",
      "$ref": "#/definitions/version"
    },
    "parent": {
      "description": "Inherit another configuration",
      "$ref": "#/definitions/version"
    },
    "commands": {
      "description": "Command definitions (opcodes as keys)",
      "type": "object",
      "patternProperties": {
        "^(\\d+|0x[\\da-fA-F]+)$": {
          "$ref": "#/definitions/command"
        }
      }
    },
    "enums": {
      "type": "object",
      "patternProperties": {
        "^([A-Z0-9_]+)$": {
          "anyOf":[
            {
              "type": "array",
              "items": {
                "type": "string",
                "pattern": "^([A-Z0-9_]+)$"
              }
            },
            {
              "type": "object",
              "patternProperties": {
                "^([A-Z0-9_]+)$": {
                  "type": "integer"
                }
              },
              "additionalProperties": false
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "debug": {
      "type": "object"
    }
  },
  "required": [ "version" ],
  "additionalProperties": false
}

=== nick7/idascm-data/gtavc/gtavc_pc.json
{
  "$schema": "../schema/configuration.json",
  "meta": {
    "timestamp": "2022-02-06T13:38:22.396304+00:00",
    "sources": [
      "https://github.com/sannybuilder/data",
      "https://github.com/sannybuilder/library"
    ]
  },
  "version": "gtavc_pc",
  "parent": "gtavc",
  "commands": {
    "0x059c": {
      "name": "SET_ONSCREEN_COUNTER_FLASH_WHEN_FIRST_DISPLAYED",
      "args": 2,
      "format": "NOP %1d% %2d%"
    },
    "0x059d": {
      "name": "SHUFFLE_CARD_DECKS",
      "args": 1,
      "format": "shuffle_card_decks %1d%",
      "comment": "never used in VC"
    },
    "0x059e": {
      "name": "FETCH_NEXT_CARD",
      "args": 1,
      "format": "get_card_to %1d%",
      "comment": "never used in VC"
    },
    "0x059f": {
      "name": "GET_OBJECT_VELOCITY",
      "args": 4,
      "format": "get_object %1d% velocity %2d% %3d% %4d%",
      "comment": "never used in VC"
    },
    "0x05a0": {
      "name": "IS_DEBUG_CAMERA_ON",
      "flags": [
        "condition"
      ],
      "format": "  is_unused_camera_world_viewer_being_used"
    },
    "0x05a1": {
      "name": "ADD_TO_OBJECT_ROTATION_VELOCITY",
      "args": 4,
      "format": "set_object %1d% rotation_velocity_about_an_axis %2d% %3d% %4d%",
      "comment": "never used in VC"
    },
    "0x05a2": {
      "name": "SET_OBJECT_ROTATION_VELOCITY",
      "args": 4,
      "format": "set_object %1d% rotation_velocity_about_an_axis %2d% %3d% %4d%",
      "comment": "never used in VC"
    },
    "0x05a3": {
      "name": "IS_OBJECT_STATIC",
      "args": 1,
      "flags": [
        "condition"
      ],
      "format": "  object %1d% stopped",
      "comment": "never used in VC"
    },
    "0x05a4": {
      "name": "GET_ANGLE_BETWEEN_2D_VECTORS",
      "args": 5,
      "format": "get_angle_between_vectors_origin_to %1d% %2d% and_origin_to %3d% %4d% store_to %5d%",
      "comment": "never used in VC"
    },
    "0x05a5": {
      "name": "DO_2D_RECTANGLES_COLLIDE",
      "args": 8,
      "flags": [
        "condition"
      ],
      "format": "  is_area_center %1d% %2d% scale %3d% %4d% overlaping_area_center %5d% %6d% scale %7d% %8d%"
    },
    "0x05a6": {
      "name": "GET_OBJECT_ROTATION_VELOCITY",
      "args": 4,
      "format": "get_object %1d% rotation_velocity %2d% %3d% %4d%",
      "comment": "never used in VC"
    },
    "0x05a7": {
      "name": "ADD_VELOCITY_RELATIVE_TO_OBJECT_VELOCITY",
      "args": 4,
      "format": "set_object %1d% velocity %2d% %3d% %4d%",
      "comment": "never used in VC"
    },
    "0x05a8": {
      "name": "GET_OBJECT_SPEED",
      "args": 2,
      "format": "get_object %1d% speed_to %2d%",
      "comment": "never used in VC"
    }
  },
  "debug": {
    "unsupported": []
  }
}

=== nick7/idascm-data/gtasa/gtasa_ps2.json
{
  "$schema": "../schema/configuration.json",
  "meta": {
    "timestamp": "2022-02-06T13:38:23.313850+00:00",
    "sources": [
      "https://github.com/sannybuilder/data",
      "https://github.com/sannybuilder/library"
    ]
  },
  "version": "gtasa_ps2",
  "parent": "gtasa",
  "commands": {
    "0x0a49": {
      "name": "DO_DEBUG_STUFF",
      "flags": [
        "condition"
      ],
      "format": "  NOP_false",
      "desc": "Returns true for Xbox versions of the game"
    }
  },
  "debug": {
    "unsupported": []
  }
}

=== nick7/idascm-data/gtasa/gtasa_pc.json
{
  "$schema": "../schema/configuration.json",
  "meta": {
    "timestamp": "2022-02-06T13:38:23.450485+00:00",
    "sources": [
      "https://github.com/sannybuilder/data",
      "https://github.com/sannybuilder/library"
    ]
  },
  "version": "gtasa_pc",
  "parent": "gtasa",
  "commands": {
    "0x0a49": {
      "name": "IS_XBOX_VERSION",
      "flags": [
        "condition"
      ],
      "format": "  NOP_false",
      "desc": "Returns true for Xbox versions of the game"
    },
    "0x0a4a": {
      "name": "GET_PC_MOUSE_MOVEMENT",
      "args": [
        "int",
        "int"
      ],
      "format": "store_joystick_X_offset_to %1h% Y_offset_to %2h%",
      "desc": "Gives the offset of the mouse or right thumbstick movement"
    },
    "0x0a4b": {
      "name": "IS_PC_USING_JOYPAD",
      "flags": [
        "condition"
      ],
      "format": "  controls_set_to_joystick",
      "desc": "Returns true if players controls are set to joystick and not mouse+keyboard"
    },
    "0x0a4c": {
      "name": "IS_MOUSE_USING_VERTICAL_INVERSION",
      "flags": [
        "condition"
      ],
      "format": "  mouse_not_inverted_vertically",
      "desc": "Returns true if the players settings are set to invert the mouse"
    },
    "0x0a4d": {
      "name": "IS_JAPANESE_VERSION",
      "flags": [
        "condition"
      ],
      "format": "  NOP_false",
      "desc": "Returns true for Japanese versions of the game"
    },
    "0x0a4e": {
      "name": "DO_DEBUG_STUFF",
      "format": "increment_useless_flag",
      "desc": "Returns true on Xbox versions of the game if player 2 is pressing the start button"
    }
  },
  "debug": {
    "unsupported": []
  }
}

=== nick7/idascm-data/gtavc/gtavc_definitive.json
{
  "$schema": "../schema/configuration.json",
  "meta": {
    "timestamp": "2022-02-06T13:38:22.660597+00:00",
    "sources": [
      "https://github.com/sannybuilder/data",
      "https://github.com/sannybuilder/library"
    ]
  },
  "version": "gtavc_definitive",
  "parent": "gtavc",
  "commands": {
    "0x059c": {
      "name": "SET_ONSCREEN_COUNTER_FLASH_WHEN_FIRST_DISPLAYED",
      "args": 2,
      "format": "NOP %1d% %2d%"
    },
    "0x059d": {
      "name": "SHUFFLE_CARD_DECKS",
      "args": 1,
      "format": "shuffle_card_decks %1d%",
      "comment": "never used in VC"
    },
    "0x059e": {
      "name": "FETCH_NEXT_CARD",
      "args": 1,
      "format": "get_card_to %1d%",
      "comment": "never used in VC"
    },
    "0x059f": {
      "name": "GET_OBJECT_VELOCITY",
      "args": 4,
      "format": "get_object %1d% velocity %2d% %3d% %4d%",
      "comment": "never used in VC"
    },
    "0x05a0": {
      "name": "IS_DEBUG_CAMERA_ON",
      "flags": [
        "condition"
      ],
      "format": "  is_unused_camera_world_viewer_being_used"
    },
    "0x05a1": {
      "name": "ADD_TO_OBJECT_ROTATION_VELOCITY",
      "args": 4,
      "format": "set_object %1d% rotation_velocity_about_an_axis %2d% %3d% %4d%",
      "comment": "never used in VC"
    },
    "0x05a2": {
      "name": "SET_OBJECT_ROTATION_VELOCITY",
      "args": 4,
      "format": "set_object %1d% rotation_velocity_about_an_axis %2d% %3d% %4d%",
      "comment": "never used in VC"
    },
    "0x05a3": {
      "name": "IS_OBJECT_STATIC",
      "args": 1,
      "flags": [
        "condition"
      ],
      "format": "  object %1d% stopped",
      "comment": "never used in VC"
    },
    "0x05a4": {
      "name": "GET_ANGLE_BETWEEN_2D_VECTORS",
      "args": 5,
      "format": "get_angle_between_vectors_origin_to %1d% %2d% and_origin_to %3d% %4d% store_to %5d%",
      "comment": "never used in VC"
    },
    "0x05a5": {
      "name": "DO_2D_RECTANGLES_COLLIDE",
      "args": 8,
      "flags": [
        "condition"
      ],
      "format": "  is_area_center %1d% %2d% scale %3d% %4d% overlaping_area_center %5d% %6d% scale %7d% %8d%"
    },
    "0x05a6": {
      "name": "GET_OBJECT_ROTATION_VELOCITY",
      "args": 4,
      "format": "get_object %1d% rotation_velocity %2d% %3d% %4d%",
      "comment": "never used in VC"
    },
    "0x05a7": {
      "name": "ADD_VELOCITY_RELATIVE_TO_OBJECT_VELOCITY",
      "args": 4,
      "format": "set_object %1d% velocity %2d% %3d% %4d%",
      "comment": "never used in VC"
    },
    "0x05a8": {
      "name": "GET_OBJECT_SPEED",
      "args": 2,
      "format": "get_object %1d% speed_to %2d%",
      "comment": "never used in VC"
    },
    "0x05a9": {
      "name": "MARK_CUTSCENE_START",
      "args": 1,
      "format": "get_mission_skip_level %1d%",
      "comment": "vcmobile opcodes"
    },
    "0x05aa": {
      "name": "MARK_CUTSCENE_END",
      "args": 1,
      "format": "set_is_in_ammunation_button_icon %1d%",
      "comment": "vcmobile opcodes"
    },
    "0x05ab": {
      "name": "CUTSCENE_SCROLL",
      "args": 1,
      "format": "set_savegame_for_pause %1d%",
      "comment": "vcmobile opcodes"
    },
    "0x05ac": {
      "name": "SET_LVAR_TEXT_LABEL_TO_LVAR_TEXT_LABEL",
      "args": 1,
      "format": "get_mission_replay %1d%",
      "comment": "vcmobile opcodes"
    },
    "0x05ad": {
      "name": "SET_VAR_TEXT_LABEL_TO_LVAR_TEXT_LABEL",
      "flags": [
        "unsupported"
      ]
    },
    "0x05ae": {
      "name": "SET_LVAR_TEXT_LABEL_TO_VAR_TEXT_LABEL",
      "flags": [
        "unsupported"
      ]
    },
    "0x05af": {
      "name": "VAR_TEXT_LABEL",
      "args": [
        "global_string"
      ],
      "flags": [
        "unsupported"
      ]
    },
    "0x05b0": {
      "name": "LVAR_TEXT_LABEL",
      "args": [
        "local_string"
      ],
      "flags": [
        "unsupported"
      ]
    },
    "0x05b1": {
      "name": "IS_TEXT_LABEL_VAR_EQUAL_TO_TEXT_LABEL",
      "flags": [
        "unsupported"
      ]
    },
    "0x05b2": {
      "name": "IS_TEXT_LABEL_LVAR_EQUAL_TO_TEXT_LABEL",
      "flags": [
        "unsupported"
      ]
    },
    "0x05b3": {
      "name": "IS_TEXT_LABEL_VAR_EQUAL_TO_TEXT_LABEL_VAR",
      "flags": [
        "unsupported"
      ]
    },
    "0x05b4": {
      "name": "IS_TEXT_LABEL_LVAR_EQUAL_TO_TEXT_LABEL_LVAR",
      "flags": [
        "unsupported"
      ]
    },
    "0x05b5": {
      "name": "IS_TEXT_LABEL_VAR_EQUAL_TO_TEXT_LABEL_LVAR",
      "flags": [
        "unsupported"
      ]
    },
    "0x05b6": {
      "name": "DO_2D_LINES_INTERSECT",
      "flags": [
        "unsupported"
      ]
    },
    "0x05b7": {
      "name": "GET_2D_LINES_INTERSECT_POINT",
      "flags": [
        "unsupported"
      ]
    },
    "0x05b8": {
      "name": "IS_2D_POINT_IN_TRIANGLE",
      "flags": [
        "unsupported"
      ]
    },
    "0x05b9": {
      "name": "IS_2D_POINT_IN_RECTANGLE_ON_LEFT_SIDE_OF_LINE",
      "flags": [
        "unsupported"
      ]
    },
    "0x05ba": {
      "name": "IS_2D_POINT_ON_LEFT_SIDE_OF_2D_LINE",
      "flags": [
        "unsupported"
      ]
    },
    "0x05bb": {
      "name": "CHAR_LOOK_AT_OBJECT_ALWAYS",
      "flags": [
        "unsupported"
      ]
    },
    "0x05bc": {
      "name": "APPLY_COLLISION_ON_OBJECT",
      "flags": [
        "unsupported"
      ]
    },
    "0x05bd": {
      "name": "SAVE_STRING_TO_DEBUG_FILE",
      "args": [
        {
          "type": "string",
          "operand_type": "string128"
        }
      ],
      "flags": [
        "unsupported"
      ]
    },
    "0x0dd0": {
      "args": [
        "any",
        "address"
      ],
      "format": "%1d% = get_label_addr %2p%",
      "comment": "android"
    },
    "0x0dd1": {
      "args": 2,
      "format": "%1d% = get_func_addr_by_cstr_name %2d%",
      "comment": "android"
    },
    "0x0dd2": {
      "args": 1,
      "format": "context_call_func %1d%",
      "comment": "android"
    },
    "0x0dd3": {
      "args": 2,
      "format": "context_set_reg %1d% value %2d%",
      "comment": "android"
    },
    "0x0dd4": {
      "args": 2,
      "format": "%1d% = context_get_reg %2d%",
      "comment": "android"
    },
    "0x0dd6": {
      "args": 1,
      "format": "%1d% = get_game_version",
      "comment": "android"
    },
    "0x0dd7": {
      "args": 1,
      "format": "%1d% = get_image_base",
      "comment": "android"
    },
    "0x0dd8": {
      "args": 4,
      "format": "%1d% = read_mem_addr %2d% size %3d% add_ib %4d%",
      "comment": "android"
    },
    "0x0dd9": {
      "args": 5,
      "format": "write_mem_addr %1d% value %2d% size %3d% add_ib %4d% protect %5d%",
      "comment": "android"
    },
    "0x0ddc": {
      "args": 2,
      "format": "set_mutex_var %1d% to %2d%",
      "comment": "android"
    },
    "0x0ddd": {
      "args": 2,
      "format": "%1d% = get_mutex_var %2d%",
      "comment": "android"
    },
    "0x0de0": {
      "args": 3,
      "format": "%1d% = get_touch_point_state %2d% mintime %3d%",
      "comment": "android"
    },
    "0x0de1": {
      "args": 5,
      "format": "%1d% = get_touch_slide_state from %2d% to %3d% mintime %4d% maxtime %5d%",
      "comment": "android"
    },
    "0x0de2": {
      "args": 1,
      "format": "%1d% = get_menu_button_state",
      "comment": "read opcode info before using ; android"
    },
    "0x0de3": {
      "args": 2,
      "format": "%1d% = get_menu_button_pressed mintime %2d%",
      "comment": "read opcode info before using ; android"
    }
  },
  "debug": {
    "unsupported": [
      "SET_VAR_TEXT_LABEL_TO_LVAR_TEXT_LABEL",
      "SET_LVAR_TEXT_LABEL_TO_VAR_TEXT_LABEL",
      "VAR_TEXT_LABEL",
      "LVAR_TEXT_LABEL",
      "IS_TEXT_LABEL_VAR_EQUAL_TO_TEXT_LABEL",
      "IS_TEXT_LABEL_LVAR_EQUAL_TO_TEXT_LABEL",
      "IS_TEXT_LABEL_VAR_EQUAL_TO_TEXT_LABEL_VAR",
      "IS_TEXT_LABEL_LVAR_EQUAL_TO_TEXT_LABEL_LVAR",
      "IS_TEXT_LABEL_VAR_EQUAL_TO_TEXT_LABEL_LVAR",
      "DO_2D_LINES_INTERSECT",
      "GET_2D_LINES_INTERSECT_POINT",
      "IS_2D_POINT_IN_TRIANGLE",
      "IS_2D_POINT_IN_RECTANGLE_ON_LEFT_SIDE_OF_LINE",
      "IS_2D_POINT_ON_LEFT_SIDE_OF_2D_LINE",
      "CHAR_LOOK_AT_OBJECT_ALWAYS",
      "APPLY_COLLISION_ON_OBJECT",
      "SAVE_STRING_TO_DEBUG_FILE"
    ]
  }
}

=== nick7/idascm-data/gtavc/gtavc_ps2.json
{
  "$schema": "../schema/configuration.json",
  "meta": {
    "timestamp": "2022-02-06T13:38:22.227756+00:00",
    "sources": [
      "https://github.com/sannybuilder/data",
      "https://github.com/sannybuilder/library"
    ]
  },
  "version": "gtavc_ps2",
  "parent": "gtavc",
  "commands": {},
  "debug": {
    "unsupported": []
  }
}

=== nick7/idascm-data/gta3/gta3_ps2.json
{
  "$schema": "../schema/configuration.json",
  "meta": {
    "timestamp": "2022-02-06T13:38:21.773970+00:00",
    "sources": [
      "https://github.com/sannybuilder/data",
      "https://github.com/sannybuilder/library"
    ]
  },
  "version": "gta3_ps2",
  "parent": "gta3",
  "commands": {},
  "debug": {
    "unsupported": []
  }
}
